### ISSUE TITLE
Can't download version manifest, while there aren't any network issues.

### ISSUE THREAD

**Issue by QboiDev** [MinecraftForge/Installer#69]
I tried to make a Minecraft 1.16.5 server with forge 36.2.0, but it can't download the version manifest on the launcher meta of mojang.  
I have checked internet connection but that's just fine.  
Also, this happens every time I install with the server option, client option works just fine.
  
I'm using Java 1.8.0 Build 312 (Eclipse Temurin). And should be compatible.  
And if I open `launchermeta.mojang.com` in browser it just gets an access denied (which isn't an unknown host or something):
```xml
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>GP11CS5984S5534M</RequestId>
    <HostId>...</HostId>
</Error>
```
*Removed the host id, because idk if it's private or not.*  
Both the check on the website and the log where both done on the same machine, and connected with the same network connection.  

```
JVM info: Temurin - 1.8.0_312 - 25.312-b07
java.net.preferIPv4Stack=true
Found java version 1.8.0_312
<html><a href='https://www.creeperhost.net/'>Data kindly mirrored by CreeperHost</a></html>
Extracting main jar:
  Extracted successfully
Considering minecraft server jar
java.net.UnknownHostException: launchermeta.mojang.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:288)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1567)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
        at net.minecraftforge.installer.DownloadUtils.getConnection(DownloadUtils.java:203)
        at net.minecraftforge.installer.DownloadUtils.downloadManifest(DownloadUtils.java:267)
        at net.minecraftforge.installer.json.Util.getVanillaVersion(Util.java:62)
        at net.minecraftforge.installer.actions.ServerInstall.run(ServerInstall.java:70)
        at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:424)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:170)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:143)
Failed to download version manifest, can not find server jar URL.
```
![image](https://user-images.githubusercontent.com/30625109/141823638-cef73354-23b4-4a04-bfef-8559666cfd53.png)

I hope this is enough information.

**Comment by TheCurle** [comment]
launchermeta.mojang.com isn't supposed to be browsable by users. It contains files that you can only read with a direct link.

However, the "unknown host" error message means there *is* a network error occurring.

I suggest you move to the [support forum](https://forums.minecraftforge.net/) for more help, as this is off topic for Github.
